### ISSUE TITLE
tidak ada info ketika chrome sudah terbuka sebelumnya

### ISSUE THREAD

**Issue by lurahxp** [WhatsAppNETClient/WhatsAppNETClient#1]
ketika close program, tanpa klik stop, maka chrome juga masih aktif(its ok)
maka ketika running lagi, kemudian tekan tombol start, maka tidak ada notif jika wasap sudah terbuka sebelumnya di chrome
mohon diberi notif, jika memang sudah ada wa chrome yg terbuka, maka ada notif bahwa sudah terbuka di chrome lain

**Comment by coding4ever** [comment]
Terima kasih om atas laporannya, sebenarnya issue ini memang sudah saya ketahui tapi karena solusinya masih bisa dihandle secara manual jadi memang belum saya tambahkan notifikasi untuk issue ini.
