### ISSUE TITLE
Bagaimana cara mengetahui pesan telah dikirim? 

### ISSUE THREAD

**Issue by ardhityawiedhairawan** [WhatsAppNETClient/WhatsAppNETClient#10]
Salam,
Sebelumnya saya ucapkan banyak terima kasih kepada pengembang. Saya saat ini sedang berusaha menggunakan dll yang tersedia di project ini. Ada sedikit pertanyaan : 
Bagaimana cara mengetahui pesan telah selesai dikirim saat menggunakan fungsi ini _whatsAppApi.SendMessage ? atau minimal mengetahui proses tersebut telah selesai dilakukan.

Terima kasih.

**Comment by pascaldhika** [comment]
https://github.com/WhatsAppNETClient/WhatsAppNETClient/issues/6#issuecomment-719880245

sdh pernah di jwb di issue ini om

**Comment by WhatsAppNETClient** [comment]
Tq om @pascaldhika  atas infonya

**Comment by ardhityawiedhairawan** [comment]
Terima kasih jawabannya, sangat membantu.
