### ISSUE TITLE
Grab Contact apakah memungkinkan mendapatkan data nomor Telepon-nya ?

### ISSUE THREAD

**Issue by mywahyudc** [WhatsAppNETClient/WhatsAppNETClient#11]
sekarang jika di klik tombol grab contact hanya mendapatkan data nomor urut dan nama contact saja,
 apakah memungkinkan mendapatkan data nomor hp juga ?

**Comment by WhatsAppNETClient** [comment]
Sudah support di versi terbaru, silahkan download ulang sample projectnya di https://github.com/WhatsAppNETClient/WhatsAppNETClient2

Dan ikuti petunjuk instalasinya:

![03 - petunjuk instalasi](https://user-images.githubusercontent.com/67818764/126947301-c95ab6ce-25f2-4b5f-bfed-56a8127fa611.JPG)
