### ISSUE TITLE
Pesan tidak terkirim dan grab contact error 

### ISSUE THREAD

**Issue by ayahabidzar** [WhatsAppNETClient/WhatsAppNETClient#12]
saya tes kirim pesan hari ini error, hari sebelum nya bisa, dan ketika klik grab contact muncul error "javascript error : cannot set property 'scrollTop' of null (session info : chrome=88.0.4324.190)

**Comment by pascaldhika** [comment]
untuk connect ke whatsapp web nya apakah berhasil? Sepertinya ada perubahan element di whatsapp web

**Comment by ayahabidzar** [comment]
connect ke whatsaap web nya berhasil , untuk kirim nya yang tidak bisa.

**Comment by agungstiawan** [comment]
Saya juga menglami hal yang sama. waktu kirim pesan tidak terkirim dan tidak ada notif apakah sukses, gagal atau error. dan ketika klik Grab Contact pun langsung error "javascript error : cannot set property 'scrollTop' of null. sudah saya coba install ulang chrome dan sesuaikan versi chromedrivernya  mulai dari crome versi 87 sampe yang terbaru tapi hasilnya sama saja. Apakah sudah ada solusinya?

**Comment by pascaldhika** [comment]
nunggu update dari develepor nya

**Comment by fiedzback** [comment]
Saya juga mengalami hal sama di chrome versi 89.0.4389.82

**Comment by WhatsAppNETClient** [comment]
> 
> 
> untuk connect ke whatsapp web nya apakah berhasil? Sepertinya ada perubahan element di whatsapp web

Betul om, sudah saya update utk perubahan element wa webnya, silahkan dicoba lagi

**Comment by ayahabidzar** [comment]
Mantap work om
