### ISSUE TITLE
Error WhatsAppNETAPI

### ISSUE THREAD

**Issue by R14L** [WhatsAppNETClient/WhatsAppNETClient#14]
Message error "the CLR has been unable to transition from COM"

**Comment by WhatsAppNETClient** [comment]
Sudah saya perbaiki di versi terbaru, silahkan download ulang sample projectnya di https://github.com/WhatsAppNETClient/WhatsAppNETClient2

Dan ikuti petunjuk instalasinya:

![03 - petunjuk instalasi](https://user-images.githubusercontent.com/67818764/126947301-c95ab6ce-25f2-4b5f-bfed-56a8127fa611.JPG)
