### ISSUE TITLE
Tidak Bisa Kirim Gambar/File

### ISSUE THREAD

**Issue by yosefnic0927** [WhatsAppNETClient/WhatsAppNETClient#15]
Setelah Klik Tombol Start, wa sudah Konek tetapi cursor hanya wait terus, tombol Kirim tidak enable (While (!_whatsapp.OnReady())
Saya mencoba untuk kirim pesan WA menggunakan Gambar/File, tetapi tidak terkirim? apakah ada perubahan API WhatsApp?

**Comment by WhatsAppNETClient** [comment]
Sudah support di versi terbaru, silahkan download ulang sample projectnya di https://github.com/WhatsAppNETClient/WhatsAppNETClient2
