### ISSUE TITLE
Bagaimana untuk terima gambar ?

### ISSUE THREAD

**Issue by oniaf** [WhatsAppNETClient/WhatsAppNETClient#3]
Apa belum ada modul untuk terima gambar ya ? ^_^
jika misal ada yang kirim gambar untuk kita terima lalu di simpan begitu ?
terima kasih responnya

**Comment by virgoid** [comment]
ia sama tidak ada respon

**Comment by coding4ever** [comment]
> 
> 
> Apa belum ada modul untuk terima gambar ya ? ^_^
> jika misal ada yang kirim gambar untuk kita terima lalu di simpan begitu ?
> terima kasih responnya

Belum support om
