### ISSUE TITLE
Bug Kirim pesan 

### ISSUE THREAD

**Issue by bpaandro84** [WhatsAppNETClient/WhatsAppNETClient#5]
Saat Kirim pesan, pesan sering tidak sampai. padahal status koneksi sudah konek.
 terdapat pesan di output The thread 0x1880 has exited with code 259 (0x103), apa yang menyebabkan hal seperti ini ?

**Comment by WhatsAppNETClient** [comment]
Dicoba lagi om

**Comment by bpaandro84** [comment]
Ok mas, mantap udah lancar saat kirim pesan. penyebabnya apa ya?

**Comment by WhatsAppNETClient** [comment]
Karena ada perubahan element css dari WhatsApp webnya
