### ISSUE TITLE
Cara untuk mengetahui pesan sudah terkirim atau gagal kirim ?

### ISSUE THREAD

**Issue by bpaandro84** [WhatsAppNETClient/WhatsAppNETClient#6]
Bagaimana caranya mengetahui pesan terkirim atau gagal terkirim ?

**Comment by WhatsAppNETClient** [comment]
Tinggal aktifkan pilihan Subscribe di tab pesan keluar

![subscribe](https://user-images.githubusercontent.com/67818764/97770819-59f9ef00-1b69-11eb-9ee9-70dfac577802.png)

**Comment by bpaandro84** [comment]
sip mas berjalan lancar.
