### ISSUE TITLE
Setelah menekan tombol start tidak terjadi apa-apa

### ISSUE THREAD

**Issue by Azzammi** [WhatsAppNETClient/WhatsAppNETClient#7]
- Sudah mengcopy chromedriver.exe dari libs ke bin/debug
- Chrome Version 86.0.4240.111 (Official Build) (64-bit)

Kenapa ya?

**Comment by WhatsAppNETClient** [comment]
Coba download ChromeDriver terbaru menyesuaikan dengan versi Chrome Browser yg di pake

https://chromedriver.chromium.org/downloads

**Comment by Azzammi** [comment]
Okee, worked pak. Terima kasih
