### ISSUE TITLE
bagaimama menampilkan nomor WA waktu terima pesan untuk nomor yang udah disimpan di kontak?

### ISSUE THREAD

**Issue by mr-habibie** [WhatsAppNETClient/WhatsAppNETClient#8]
Bisa tidak menampilkan nomor WA waktu terima pesan yang nomornya udah disimpan dikontak? soalnya kalau pakai e.Sender keluarnya Nama kalau udah disimpan di kontak

**Comment by WhatsAppNETClient** [comment]
> 
> 
> Bisa tidak menampilkan nomor WA waktu terima pesan yang nomornya udah disimpan dikontak? soalnya kalau pakai e.Sender keluarnya Nama kalau udah disimpan di kontak

Untuk saat ini belum support om

**Comment by indranoprida** [comment]
untuk menghubungkan ke mysql gimna ya?

**Comment by WhatsAppNETClient** [comment]
> Bisa tidak menampilkan nomor WA waktu terima pesan yang nomornya udah disimpan dikontak? soalnya kalau pakai e.Sender keluarnya Nama kalau udah disimpan di kontak

Sudah support di versi terbaru, silahkan download ulang sample projectnya di https://github.com/WhatsAppNETClient/WhatsAppNETClient2

Dan ikuti petunjuk instalasinya:

![03 - petunjuk instalasi](https://user-images.githubusercontent.com/67818764/126947301-c95ab6ce-25f2-4b5f-bfed-56a8127fa611.JPG)

**Comment by WhatsAppNETClient** [comment]
> untuk menghubungkan ke mysql gimna ya?

Ya tinggal di program sendiri
