### ISSUE TITLE
Nomor tidak terdaftar di whatsapp

### ISSUE THREAD

**Issue by pascaldhika** [WhatsAppNETClient/WhatsAppNETClient#9]
Whatsapp Broadcast saya ada bug terkadang jika kirim ke nomor yg tidak terdaftar di whatsapp tidak masuk event _OnMessageSentEventHandler_

stuck disini :

![phone number invalid](https://user-images.githubusercontent.com/33945881/102442133-3a098680-4056-11eb-94cc-7aa9c54a300f.png)

**Comment by WhatsAppNETClient** [comment]
Saya udah coba broadcast message ke beberapa nomor yg enggak valid tetap bisa om

**Comment by pascaldhika** [comment]
apa karna ada pengaruh dari perubahan codingan saya ya pak. Saya sdh custom source codenya. Salah satunya broadcast message ambil dari database postgre

**Comment by WhatsAppNETClient** [comment]
Klo langsung nyoba source code contoh aslinya muncul asus yang sama enggak om?

**Comment by pascaldhika** [comment]
![Screenshot_49](https://user-images.githubusercontent.com/33945881/103273760-a4c1a700-49f2-11eb-8666-3e97cf02c510.png)

sama error juga pak

**Comment by ardhityawiedhairawan** [comment]
Saya mengalami ini juga. Tapi anehnya kadang kejadiannya random. Terkadang popup itu otomatis tertutup, tapi terkadang tidak otomatis tertutup. Nah kalau pas ngga otomatis tertutup itu membuat tidak bisa lanjut proses selanjutnya (broadcast). 

btw, saya tidak pakai fungsi broadcastnya, tapi saya pakai timer untuk mengambil data dari database, lalu mengirimnya satu per satu.

**Comment by pascaldhika** [comment]
> 
> 
> Saya mengalami ini juga. Tapi anehnya kadang kejadiannya random. Terkadang popup itu otomatis tertutup, tapi terkadang tidak otomatis tertutup. Nah kalau pas ngga otomatis tertutup itu membuat tidak bisa lanjut proses selanjutnya (broadcast).
> 
> btw, saya tidak pakai fungsi broadcastnya, tapi saya pakai timer untuk mengambil data dari database, lalu mengirimnya satu per satu.

iya sama om. saya juga pernah pakai timer kirim satu per satu terkadang popup nya tdk tertutup otomatis

**Comment by WhatsAppNETClient** [comment]
Sudah saya perbaiki di versi terbaru, silahkan download ulang sample projectnya di https://github.com/WhatsAppNETClient/WhatsAppNETClient2

Dan ikuti petunjuk instalasinya:

![03 - petunjuk instalasi](https://user-images.githubusercontent.com/67818764/126947301-c95ab6ce-25f2-4b5f-bfed-56a8127fa611.JPG)

**Comment by pascaldhika** [comment]
terimakasih pak. di versi terbaru sdh tdk tergantung pada perubahan element wa web nya ya pak?

**Comment by WhatsAppNETClient** [comment]
> terimakasih pak. di versi terbaru sdh tdk tergantung pada perubahan element wa web nya ya pak?

Iya om, insyaAlloh udah aman
